# alpine linux included openjdk 17
FROM openjdk:17-alpine

# project directory
ENV project="camila"

# set timezone
RUN apk add tzdata && ln -snf /usr/share/zoneinfo/Asia/Seoul /etc/localtime

# create project directory
RUN mkdir ${project}

#COPY : from local jar to docker imags 
COPY build/libs/*.jar /${project}/${project}_dt.jar

# exec jar without env
ENTRYPOINT ["sh", "-c", "java -jar -Dspring.profiles.active=dt /${project}/${project}_dt.jar"]